meta_product_name: "Rocketly • Boost fans engagement"
meta_title: "Rocketly • Level-up your fans"
meta_description: "Rocketly is the best way to engage your top fans in your creative activity"
meta_image: "rocketly_banner.jpg" # should exist in `app/assets/images/`
twitter_account: "@1maaaat"   # required for Twitter Cards
